Repository flocasts/nestjs-google-pubsub-connector, pull requests merged in 2021-04, with the labels that each got.

#37 feat(server): add topic naming strategy interface
  lib/interfaces.ts
  lib/server/server-google-pubsub.ts
  lib/strategies/basic-topic-naming-strategy.spec.ts
  lib/strategies/basic-topic-naming-strategy.ts
  package-lock.json
  package.json
Labels: enhancement

#36 docs: add typedoc for generating a documentation site
  .gitignore
  lib/client/client-google-pubsub.ts
  package-lock.json
  package.json
  typedoc.json
Labels: documentation

#39 fix(server): prevent decorator arg ordering from preventing handler lookup
  lib/server/server-google-pubsub.ts
  test/server/server.e2e-spec.ts
Labels: bug

#44 Server refactors
  lib/errors/transport-error.exception.ts
  lib/server/server-google-pubsub.ts
Labels: wip

#46 ci(tsdoc): deploy documentation to github pages
  deploy/deploy-package.yaml
  package-lock.json
  package.json
Labels: documentation

#50 fix(server): use existing subscription if it already exists
  README.md
  lib/interfaces.ts
  lib/server/server-google-pubsub.spec.ts
  lib/server/server-google-pubsub.ts
  lib/strategies/basic-subscription-naming-strategy.spec.ts
  lib/strategies/basic-subscription-naming-strategy.ts
Labels: bug, transport strategy

#49 docs: deploy docs using post-push hook
  .husky/post-push
  package.json
Labels: documentation

#52 fix(server): use topic naming strategy to create topic names
  lib/server/server-google-pubsub.ts
Labels: bug
